---
# tasks file for docker-compose-service
- name: Creating tools directory
  file:
    path: "{{tools_path}}/"
    state: "directory"

- name: Deploying tools
  template:
    src: "{{item}}"
    dest: "{{tools_path}}/"
    mode: 0744
  with_items:
    - "pre-start.sh"
    - "stop.sh"

- name: Creating servcies root folder
  file:
    path: "{{services_root}}/"
    state: "directory"

- name: Deploying environment file
  template:
    src:  "{{env_file}}"
    dest: "{{target_env_file}}"
  when: env_file != ""

- name: Deploying service
  template:
    src: docker-compose@.service
    dest: /etc/systemd/system/
    mode: 0644
